version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    ports:
      - "7000:7000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gosotral_user
      POSTGRES_PASSWORD: gosotral_pass
      POSTGRES_DB: gosotral_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
